name: Despliegue a AwardSpace

on:
  push:
    branches:
      - main  # Se ejecutarÃ¡ cada vez que subas cambios a la rama main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Obtener cÃ³digo actual
      uses: actions/checkout@v3

    - name: ðŸ“‚ Sincronizar archivos por FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./     # Carpeta de tu repo que quieres subir
        server-dir: ./    # Ajusta esto segÃºn la ruta de AwardSpace (ej: /tu-dominio.com/htdocs/)
